### PR TITLE
Add Indonesian Languages

### PR DESCRIPTION
**Pull request by keenanyafiqy**

### CODE REVIEW

**Comment by keenanyafiqy** [comment]
okay.. this time don't too messed up

**Comment by keenanyafiqy** [comment]
nvm, chose the latest

**Comment by Benedikt05** [comment]
Ok, I will add it

**Comment by VaxPex** [comment]
Idk if its right but i will merge it

**Comment by keenanyafiqy** [comment]
there's nothing wrong with the language. i have fixed some

**Comment by VaxPex** [comment]
Are u sure?

**Pull request merged**
