### PR TITLE
Fix anvil

### PR DESCRIPTION
**Pull request by FurkanYks**
## Introduction
 Anvil inventory works again

### issues

* Fix the error thrown during anvil action

### CODE REVIEW

**Comment by efor89** [comment]
its fix boat too?

**Comment by vp817** [comment]
ye

**Comment by vp817** [comment]
@Benedikt05

**Comment by Benedikt05** [comment]
> @Benedikt05

i cant check rn

**Comment by FurkanYks** [comment]
> it fix boat too?

yes

**Comment by Benedikt05** [comment]
@vp817 Please take care of this PR, I'm too lazy

**Comment by vp817** [comment]
> @vp817 Please take care of this PR, I'm too lazy

ok tell him to merge with the latest changes

**Pull request closed without merging**
